// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEVWjygno6zaEtPaqXdZOLdSMiG-gg4c',
    appId: '1:117688106294:web:1872462fa37e598b2f4797',
    messagingSenderId: '117688106294',
    projectId: 'ferris-app',
    authDomain: 'ferris-app.firebaseapp.com',
    storageBucket: 'ferris-app.appspot.com',
    measurementId: 'G-G4HKWXHNL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdfnbO3ob_imMeSBf7ekdqnpEgJoM6LBw',
    appId: '1:117688106294:android:a1c531d7fb1842a62f4797',
    messagingSenderId: '117688106294',
    projectId: 'ferris-app',
    storageBucket: 'ferris-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1CkCJ89fPl2p0OLJWXd7TtSvq9BZafAo',
    appId: '1:117688106294:ios:f2b1a12dd0006a942f4797',
    messagingSenderId: '117688106294',
    projectId: 'ferris-app',
    storageBucket: 'ferris-app.appspot.com',
    iosBundleId: 'com.fwtsolutions.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1CkCJ89fPl2p0OLJWXd7TtSvq9BZafAo',
    appId: '1:117688106294:ios:1154d2f426e1478d2f4797',
    messagingSenderId: '117688106294',
    projectId: 'ferris-app',
    storageBucket: 'ferris-app.appspot.com',
    iosBundleId: 'com.example.ferrisfwt.RunnerTests',
  );
}
